const data = {
    products: [
      {
        name: 'Scooter ev1',
        category: 'Scooter',
        image: '/images/steelgray.png',
        prod:'gray',
        price: 60000,
        rating: 4.2,
        numReviews: 10,
        colour:'steel gray',
        countInStock: 20,
        description: 'comfortable scooter',
      },
      {
        name: 'Scooter ev2',
        category: 'Scooter',
        image: '/images/black.jpg',
        prod:'black',
        price: 60000,
        rating: 4.2,
        numReviews: 10,
        colour:'black',
        countInStock: 20,
        description: 'comfortable scooter',
      },
      {
        name: 'Scooter ev3',
        category: 'Scooter',
        image: '/images/white.png',
        prod:'white',
        price: 60000,
        rating: 4.2,
        numReviews: 10,
        colour:'white',
        countInStock: 20,
        description: 'comfortable scooter',
      },
      {
        name: 'Scooter ev4',
        category: 'Scooter',
        image: '/images/blue.png',
        prod:'blue',
        price: 60000,
        rating: 4.2,
        numReviews: 10,
        colour:'blue',
        countInStock: 20,
        description: 'comfortable scooter',
      },
      {
        name: 'Scooter ev5',
        category: 'Scooter',
        image: '/images/green.png',
        prod:'green',
        price: 60000,
        rating: 4.2,
        numReviews: 10,
        colour:'green',
        countInStock: 20,
        description: 'comfortable scooter',
      },
      {
        name: 'Scooter ev5',
        category: 'Scooter',
        image: '/images/red.png',
        prod:'red',
        price: 60000,
        rating: 4.2,
        numReviews: 10,
        colour:'red',
        countInStock: 20,
        description: 'comfortable scooter',
      },
    ],
  };
  export default data;