const data = {
    products: [
      {
        name: 'Scooter',
        category: 'Scooter',
        image: '/images/steelgray.png',
        product:'gray',
        price: 60000,
        rating: 4.2,
        numReviews: 10,
        colour:'steel gray',
        countInStock: 20,
        description: 'comfortable scooter',
      },
      {
        name: 'Scooter',
        category: 'Scooter',
        image: '/images/black.jpg',
        price: 60000,
        rating: 4.2,
        numReviews: 10,
        colour:'black',
        countInStock: 20,
        description: 'comfortable scooter',
      },
      {
        name: 'Scooter',
        category: 'Scooter',
        image: '/images/white.png',
        price: 60000,
        rating: 4.2,
        numReviews: 10,
        colour:'white',
        countInStock: 20,
        description: 'comfortable scooter',
      },
      {
        name: 'Scooter',
        category: 'Scooter',
        image: '/images/blue.png',
        price: 60000,
        rating: 4.2,
        numReviews: 10,
        colour:'blue',
        countInStock: 20,
        description: 'comfortable scooter',
      },
      {
        name: 'Scooter',
        category: 'Scooter',
        image: '/images/green.png',
        price: 60000,
        rating: 4.2,
        numReviews: 10,
        colour:'green',
        countInStock: 20,
        description: 'comfortable scooter',
      },
      {
        name: 'Scooter',
        category: 'Scooter',
        image: '/images/red.jpg',
        price: 60000,
        rating: 4.2,
        numReviews: 10,
        colour:'red',
        countInStock: 20,
        description: 'comfortable scooter',
      },
    ],
  };
  export default data;